### ISSUE TITLE
[Bug] positioning bug with grupi/axon installed

### ISSUE THREAD

**Issue by imfaridhasan** [himynameisubik/Kalm-support#159] opened 2020-07-06 20:29 UTC
General information:
===

**Kalm version:**
2.0.2 Lastest
**Kalm preferences file:**
https://pastebin.com/wwG15dNS

Device information:
===

**iOS version and language:**
13.5 English
**Device:**
iPhone 7
**Jailbreak:**
uO Lastest

Bug description:
===

**Describe the bug:**
small issue when grupi installed with kalm.

**How to reproduce:**

install kalm and grupi, then turn on custom positioning.

**Expected behavior:**
clock shows and then fade every time i clicked on notification on grupi, i just want the old method for positioning the clock, i think its great when no notification we can move the clock to center, but if the case like me having grupi installed also it’s little bit annoying, i can’t move the clock if grupi shows notification badges.

**Screenshots:**
https://imgur.com/gallery/9lowEJD

Additional information:
===

**Tweak list:**
none

**Crashlog:**
none

**Comment by himynameisubik** [comment] 2020-07-07 07:40
Thanks for the report. This is a duplicate of #156

**Closed by himynameisubik** 2020-07-07 07:40 UTC
