### ISSUE TITLE
Duplication of custom notifications padding and alternative date font gap

### ISSUE THREAD

**Issue by CySxL** [himynameisubik/Kalm-support#163] opened 2020-07-10 17:15 UTC
General information:
===

**Kalm version:**
2.0.3
**Kalm preferences file:**
Put it on www.pastebin.com.

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

https://pastebin.com/xPDB358x

Device information:
===

**iOS version and language:**
iOS13.3, Traditional Chinese
**Device:**
iPhoneX
**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**
I can't move Grupi/Axon cell to the right place that also can display ColorFlow's album cover as well, which can be done below version 1.4.3.
**How to reproduce:**

Both adjust alternative date font gap value and Custom notifications padding's value,
you will find out no matter how u adjust them the setup below 1.4.3 can't be reproduced.

If u set a nice alternative font gap of Grupi notifications, u will notice that the top of the album cover of ColorFlow5 would overlap on alternative date, and vise versa. 

(It means that if u have set a nice custom notifications padding value which effects the album cover's position of ColorFlow5, then the cell of Grupi will not be on the right place to display but overlapping on alternative date.

So be more precisely, my request is :

Don't move the notifications padding while user change Alternative Date Font Gap, let the two functions do their work separately like what they are doing in version 1.4.3

![4B9E7B5C-B416-4461-B461-3B6CEC5BDB92](https://user-images.githubusercontent.com/15531137/87180605-700e4600-c313-11ea-8acd-0756a94c7aeb.png)

**Expected behavior:**

**Screenshots:**
![2103415D-E6EC-46B2-AA06-CAC40756E5FE](https://user-images.githubusercontent.com/15531137/87180581-6258c080-c313-11ea-894c-edd86cacd810.png)

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by CySxL** [comment] 2020-07-10 17:33
screenshot for "setting custom notifications padding well but album cover too low."

![9E6D3957-1DF1-4378-98CF-56797E173C04](https://user-images.githubusercontent.com/15531137/87182065-fd529a00-c315-11ea-8a34-38ab7f5da2d0.png)
![9D4AB13F-6310-40A1-A4C2-C9A82EDB5821](https://user-images.githubusercontent.com/15531137/87182187-35f27380-c316-11ea-9ae1-c624f5eb6e8e.png)

**Comment by CySxL** [comment] 2020-07-11 00:09
by the way
here is the setting I use in version 1.4.3 which can perfectly show alternative date/Grupi cell/ColorFlow5 album cover/NextUp2

![2BA8D320-F672-4E5C-BD33-4C68F8B059B4](https://user-images.githubusercontent.com/15531137/87211780-b2547900-c34d-11ea-9dcf-7eae4689b47f.png)
The most strange thing is with the same setting I can't achieve same result in version 2.0.0 and newer. 
![84365B1F-C46C-4A82-A929-9929198CDBD3](https://user-images.githubusercontent.com/15531137/87211770-a7014d80-c34d-11ea-8eb9-8c1ed156c1a8.png)

**Comment by CySxL** [comment] 2020-07-11 00:15
setting result screenshot in version 1.4.3:
![815F7007-3E13-4535-A32E-FC6ED2FB5C0B](https://user-images.githubusercontent.com/15531137/87211900-69e98b00-c34e-11ea-8774-9e43703584ef.png)
and i'm gonna downgrade to 1.4.3 again.

**Comment by himynameisubik** [comment] 2020-07-15 15:45
Will take a look at this.

**Comment by CySxL** [comment] 2020-07-28 03:41
Appreciate.

Kinda drive me crazy tho.

**Comment by himynameisubik** [comment] 2020-07-28 06:53
Looks like the "working" below 1.4.3 was actually a bug. Because as I see it both elements are a part of the notification list. Can you check if the position is "correct" without alt date?

**Comment by CySxL** [comment] 2020-07-28 13:31
Sure. What can do for u to provide information?
ps. I'm using 1.4.3 rn

**Comment by himynameisubik** [comment] 2020-07-28 14:20
Using 1.4.3 will not help me to fix this.

Disable the alternative date, and tell me if the position is correct then. Nobody else ever said this was wrong, and many other users use alternative date as well.

**Comment by CySxL** [comment] 2020-07-28 15:14
I told u all I can inspect lol ʕ •ᴥ•ʔ
and not letting me being crazy by waiting a fix among 1.4.3 and 2.0.3.

**Comment by CySxL** [comment] 2020-07-28 15:25
Just try 2.0.4 and still same problem : can't get all elements displayed on screen properly. 

with alternative date disabled its good, but it's because disabling it save more space to the screen, dunno why u want to do this.

And ok I'm going to fuck off all the settings and downgrade to 1.4.3

**Comment by CySxL** [comment] 2020-07-28 15:28
And also, seems like u don't get my point.

below 1.4.3 : adjusting alternative date won't influence notifications banners/cells

after 2.0.0 : adjusting alternative date will fuck my notifications padding settings as well.

**Comment by CySxL** [comment] 2020-07-28 15:29
Dunno how other users didn't encounter this damn issue but I'm tired of switching back and forth and always need to readjust my settings to fit 1.4.3 or newer.

I'm a normal user not a beta tester tho.

Thanks for update.

**Comment by himynameisubik** [comment] 2020-07-28 17:13
Can you send me an email of your Chariz receipt to cydia[at]ubikstyl.es? You use CyDown. Also you didn't upload your Tweak list.

**Comment by CySxL** [comment] 2020-07-29 00:19
u mean this?
![DB0FA866-D72C-43A6-AAE0-F0C1D209AF74](https://user-images.githubusercontent.com/15531137/88742187-29727580-d174-11ea-98d5-bc4f53208619.png)

**Comment by CySxL** [comment] 2020-07-29 00:21
OR THIS??
![34D297DE-E402-41EC-8779-B583DE27D813](https://user-images.githubusercontent.com/15531137/88742276-68083000-d174-11ea-8e18-4dd2e176991a.png)

**Comment by himynameisubik** [comment] 2020-07-29 07:13
The alignment of CF and Axon seems to be correct for me. The issue is here that the cover art is inside a "notification box", you can see that by disabling the coloring of the lockscreen.

And again, it "worked" for you on 1.4.3 because the calculation was wrong. The alignment of Axon also is different depending on the style selected.

**Comment by himynameisubik** [comment] 2020-07-29 07:13
Also please remove any "fuck" etc from your comments or I'll just have to close this issue.

**Comment by CySxL** [comment] 2020-07-29 15:39
> The alignment of CF and Axon seems to be correct for me. The issue is here that the cover art is inside a "notification box", you can see that by disabling the coloring of the lockscreen.
> 
> And again, it "worked" for you on 1.4.3 because the calculation was wrong. The alignment of Axon also is different depending on the style selected.

So can be solved or an issue that caused by conflicts ?

**Comment by himynameisubik** [comment] 2020-07-29 17:51
Your problem can't be solved since the current implementation is correct. Did you disable the coloring of the lockscreen in ColorFlow and check?

**Comment by CySxL** [comment] 2020-08-13 06:32
Nvm I just abandoned my lunar calendar to get more space and upgrade to 2.0.4

**Closed** 2020-08-13 06:33 UTC
Labels: blocked, enhancement
