### ISSUE TITLE
Safemode after installed 1.3.0

### ISSUE THREAD

**Issue by canary-yellow** [himynameisubik/Kalm-support#36] opened 2020-03-08 18:27 UTC
**Packix Username:***
harudsgn

**Describe the bug**
I just bought the kalm tweak (1.30) and went straight to safemode after I respring my springboard.

**How to reproduce**

**Expected behavior**

**Screenshots**

**iOS Version:**
12.4

**Device:**
iPhone X

**Device language:**
French

**Comment by himynameisubik** [comment] 2020-03-08 19:13
Duplicate of #37

**Closed by himynameisubik** 2020-03-08 19:13 UTC
