### ISSUE TITLE
Widget page on iPad cuts off at bottom with custom notification padding

### ISSUE THREAD

**Issue by allendude51** [himynameisubik/Kalm-support#66] opened 2020-04-15 02:19 UTC
General information:
===

**Packix username:**
Alleniscool51@gmail.com 
**Kalm version:**
1.3.4
**Kalm preferences file:**
https://pastebin.com/QLLFb9u5

Device information:
===

**iOS version and language:**
12.4.6 English 
**Device:**
iPad Air
**Jailbreak:**

Checkra1n

Bug description:
===

**Describe the bug:**
When I have a custom setting for custom notification padding (the value was a negative number), the widget page on the lockscreen displays a gap at the bottom that cuts the widgets off. I turned off the custom notification padding setting and the issue when away, but I'd like to have a custom setting without having this gap there.

**How to reproduce:**

Settings > Kalm > More > change “CUSTOM NOTIFICATION PADDING” to a negative value

**Expected behavior:**
I expected that gap to not be there.

**Screenshots:**
![0E07F41C-1627-45A2-B2C6-02284FA4A67F-3582-000004913C2EA88B](https://user-images.githubusercontent.com/51012842/79291781-29848900-7e95-11ea-9ea2-8830be1c96a7.jpeg)

Additional information:
===

**Tweak list:**
https://pastebin.com/5jJtFX00

**Crashlog:**
None

**Comment by himynameisubik** [comment] 2020-04-15 08:28
Thanks for the report, could you try to downgrade to version 1.3.2 or 1.3.1 to check if the issue persists there?

**Comment by himynameisubik** [comment] 2020-04-15 08:32
Also, kudos for the amazing report you submitted. Wish everyone would take you as an example 👍

**Comment by allendude51** [comment] 2020-04-15 18:49
Thank you. Also, I downgraded to 1.3.1 and the issue is still there

**Comment by himynameisubik** [comment] 2020-04-15 19:01
Hmm, and notifications are fine? Can't seem to find anything that would make this happen in older versions.

**Comment by allendude51** [comment] 2020-04-15 19:23
Yes notifications are fine. It's just the widgets page.

**Comment by himynameisubik** [comment] 2020-04-19 07:36
Does this also happen with all other tweaks disabled? Can't seem to reproduce on my iOS12 device. Might be exclusive to iPads on 12.

**Comment by allendude51** [comment] 2020-04-21 01:58
yes it's still there even with everything else disabled.

**Comment by himynameisubik** [comment] 2020-05-07 08:43
Unforutnately this seems to be an issue with iOS12. I can't seem to find an easy way to fix it, but I'll look into it.

**Comment by himynameisubik** [comment] 2020-06-05 13:12
Should be fixed with >1.4.0

**Closed** 2020-06-29 12:25 UTC
Labels: bug, more info
