### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by sencercebeci** [himynameisubik/Kalm-support#197] opened 2020-08-18 20:27 UTC
Hi man, after some updates (i dunno which one) that bug appears to me.

The place of the clock changes every time I turn the screen off and on.  and sometimes it gets broken.  I turned it on 3 times in a row on the screen shots.  you can examine them.
I deleted the plist file and respring it, but it didn't improve.  It has nothing to do with other tweaks because this happened after the update.

IPad Pro 10.5 
IOS : 13.5

![49ACE25A-D624-413B-BFEE-6A798DDEE6D9](https://user-images.githubusercontent.com/40920712/90562078-f08d5580-e1a1-11ea-907a-b60b7a5c1a08.jpeg)
![88B179EB-E97D-48E7-A7B1-09607EDDF60A](https://user-images.githubusercontent.com/40920712/90562084-f2efaf80-e1a1-11ea-94ce-e769a26b0f6a.jpeg)
![78B5FE4C-8CBD-4911-930E-E15BB102945B](https://user-images.githubusercontent.com/40920712/90562085-f3884600-e1a1-11ea-837e-fd9202fe992c.jpeg)

**Comment by himynameisubik** [comment] 2020-08-19 08:12
Duplicate of #188

**Closed by himynameisubik** 2020-08-19 08:12 UTC
