### ISSUE TITLE
Clock moving to top of screen, FaceID lock disappearing. 

### ISSUE THREAD

**Issue by ChefEr1c** [himynameisubik/Kalm-support#45] opened 2020-03-10 15:39 UTC
**Packix Username:***
erichobson

**Describe the bug**
Clock occasionally moves to the top of the screen and the FaceID lock disappears. 

**How to reproduce**
1. Occasionally occurs when I unlock my device. Unable to reproduce it every time. 

**Expected behavior**
Sometimes the clock looks normal, sometimes it’s somewhere it shouldn’t be. 

**Screenshots**
![B2961EDC-1668-491D-983E-88D60FBCD328](https://user-images.githubusercontent.com/47909464/76329748-59070b00-62c3-11ea-9bd9-2a8e6577f847.png)

**iOS Version:**
13.3.1
**Device:**
iPhoneX
**Device language:**
English
**Tweak list:**
https://pastebin.com/AtWKndir

**Crashlog:**
No crashlog 

**Additional context**
No additional context

**Comment by himynameisubik** [comment] 2020-03-10 15:48
Which version?

**Comment by JJGrootveld** [comment] 2020-03-10 18:20
Same issue here, the entire view is moved up randomly. Ever since version 1.3.0. I’m currently running the latest version of Kalm (1.3.2)

iOS Version:
13.3

Device:
iPhone X

Device language:
English

Tweak list:
https://pastebin.com/Lgw6ekaK

Crashlog:
No crashlog

Additional context
Happens a lot but very randomly. A simple lock / unlock usually fixes it.

Picture for reference:
![A5857AD1-7742-4360-9559-2EEB26EE1CF4](https://user-images.githubusercontent.com/9549605/76345612-f5510200-6303-11ea-9efe-584a99a8f815.jpeg)

**Comment by himynameisubik** [comment] 2020-03-10 20:08
Does it happen with only Kalm installed aswell? Could you upload your tweak list @JJGrootveld you accidentally uploaded your repos.

**Comment by JJGrootveld** [comment] 2020-03-10 20:12
crap, my bad! Updated the link :) 

To be honest I haven’t tried disabeling every other tweak yet. I’ll try that somewhere tomorrow and report back

**Comment by JJGrootveld** [comment] 2020-03-10 21:33
Checking back in. Disabled all tweaks and the issue still pops up @himynameisubik 😕

**Comment by himynameisubik** [comment] 2020-03-10 22:18
Should be fixed next version. Weirdly enough it only happens randomly and doesn't happen on my three devices :/

**Comment by JakeValenzuela** [comment] 2020-03-15 06:19
I wanted to add to this and say it also occurs randomly on my iPhone Xr on iOS 13.3. I have been experiencing it quite only since the last update and it has been occuring quite often. I'll keep my eye out for the next version to see if this is fixed.

**Comment by er1cnl** [comment] 2020-03-23 06:42
I've been having the same issue since version 1.3

it seems to happen most when lockscreen is activated by time-out, with an app still open.
if I lock my device manually from the home screen, it seems to be fine.

the only other lockscreen tweak that I am running is "Sakal"

it happens on all 1.3 versions you have released

(friends of mine have the same issue)

**Comment by himynameisubik** [comment] 2020-03-23 07:48
I try to answer a lot of tweets as well, but some slip through that's why if you have issues please use GitHub.

The problem is the same, it's just higher up because your main view with the events is larger. Will be fixed in the next update.

**Comment by himynameisubik** [comment] 2020-03-27 17:10
Kalm 1.3.3 was submitted to Packix

**Comment by himynameisubik** [comment] 2020-03-28 12:53
https://github.com/himynameisubik/Kalm-support/issues/56#issue-589571522

**Comment by JJGrootveld** [comment] 2020-03-28 12:54
Hi @himynameisubik the issue with kalm appearing off screen is still happening on the latest version

![0AA9178E-1CDE-42F0-BA06-45AA2BA05D9C](https://user-images.githubusercontent.com/9549605/77823457-9e1ca100-70fb-11ea-8548-7cc867efb28f.jpeg)

Iphone X, 13.3

**Comment by himynameisubik** [comment] 2020-03-28 14:34
@JJGrootveld Any idea _when_ it happens? Like what are you doing for example?

**Comment by zibo29** [comment] 2020-03-28 14:46
Does any of the person above has installed Lynx? Could be related to this tweak!

**Comment by JJGrootveld** [comment] 2020-03-28 14:56
> @JJGrootveld Any idea _when_ it happens? Like what are you doing for example?

Honestly I have no clue.. it totally random when unlocking my phone. Im doing nothing specific to make it go away either. I know that’s not going to help you so I’ll keep a log from now on and write down what I did when it happened and i’ll report back when I have a few instances written down.

**Comment by JJGrootveld** [comment] 2020-03-28 14:56
> Does any of the person above has installed Lynx? Could be related to this tweak!

No I do not own Lynx

**Comment by himynameisubik** [comment] 2020-03-28 15:15
@JJGrootveld Can you try using _only_ Kalm for some hours, disabling all other tweaks in iCleaner?

**Comment by JJGrootveld** [comment] 2020-03-28 15:18
@himynameisubik Yup, will do

**Comment by yonigold1** [comment] 2020-03-28 19:02
I am still having this bug on the latest version 1.3.3
[here ](https://imgur.com/gallery/MhHGXdF)  is a video showing the bug the second time the clock doesn’t move that’s what it should be like

**Comment by JJGrootveld** [comment] 2020-03-28 19:17
@himynameisubik so after a few hours with only Kalm enabled and everything else turned off through ccleaner:

Ive had it happen 5 times so far

1. Using whatsapp, closed out using homebar, locked iphone, unlocked - bug appeared
2. Had phone locked for 5 mins. Unlocked it - bug appeared
3. Same as #1 
4. Same as #1 
5. Same as #1

I havent really done much else but open whatsapp, messaging people, closing the app and noticing the bug straight after. Don’t think it’s whatsapp related but there may be something causing this  when you open other apps aswell?

**Comment by zibo29** [comment] 2020-03-28 19:24
Same as comment above, with only Kalm enable for the entire afternoon it happened like 3-4 times, for my self it was related twice to a call (as soon as I’ve ended the call the bug appeared) so I don’t really know what is triggering that

**Comment by er1cnl** [comment] 2020-03-28 19:25
for me it still looks like it happens this way:

it seems to happen most when lockscreen is activated by time-out, with an app still open.
if I lock my device manually from the home screen, it seems to be fine.

**Comment by JJGrootveld** [comment] 2020-03-28 19:26
> for me it still looks like it happens this way:
> 
> it seems to happen most when lockscreen is activated by time-out, with an app still open.
> if I lock my device manually from the home screen, it seems to be fine.

Hmm could be.. I have lock on timeout disabled on my phone though.. i always lock my phone manually :/

**Comment by zibo29** [comment] 2020-03-28 19:28
I’ll try to remove entirely Kalm, run iCleaner, reboot (just for the sake of it) and search for leftovers - I’ll report back if something changes

**Comment by zibo29** [comment] 2020-03-28 19:49
Nope, problem still present - could it be related to the custom size we use for Kalm?

**Comment by JJGrootveld** [comment] 2020-03-28 20:09
> Nope, problem still present - could it be related to the custom size we use for Kalm?

You might be on to something here.. disabling all my scaling options and will test it

**Comment by himynameisubik** [comment] 2020-03-28 21:16
Hmm, I use custom scaling all the time (nothing else tho) but the problem never happens with 1.3.3. It really rarely happened with 1.3.2 for me too. And then I changed the method that I assumed was the culprit and it went away. It just so strange because it's definitely not something everyone has.

**Comment by himynameisubik** [comment] 2020-03-28 21:19
Could you guys upload your Kalm prefs file to pastebin please?

**Comment by JJGrootveld** [comment] 2020-03-28 21:21
Nothing else as in no up next view? I’ll try disabling that.. I had 3 events for up to 7d ahead. But I doubt theres an issue there

**Comment by JJGrootveld** [comment] 2020-03-28 21:22
What is the file called? @himynameisubik

**Comment by himynameisubik** [comment] 2020-03-28 21:24
@JJGrootveld https://github.com/himynameisubik/Kalm-support : Step 5

**Comment by JJGrootveld** [comment] 2020-03-28 21:27
https://pastebin.com/Zb6sRVWN

**Comment by zibo29** [comment] 2020-03-28 23:14
Here’s mine https://pastebin.com/VST8k3Lz

**Comment by himynameisubik** [comment] 2020-03-29 13:37
Appreciate it. Will look over them and try them out on my devices.

**Comment by himynameisubik** [comment] 2020-03-29 16:00
Can you try this plist please?
https://pastebin.com/k8cxGJ8u

**Comment by zibo29** [comment] 2020-03-29 16:01
I’ll download it right now, I’ll report back

**Comment by himynameisubik** [comment] 2020-03-29 16:23
Make sure to change one setting (appe-arance f.e.) after replacing the plist

**Comment by zibo29** [comment] 2020-03-29 16:49
Ok, changed plist - respring and then changed one font size, it’s that ok?

**Comment by zibo29** [comment] 2020-03-29 18:14
Nope, problem still present

**Comment by JJGrootveld** [comment] 2020-03-29 18:15
> Nope, problem still present

Do you have a screenshot? Ive not encountered it yet..

**Comment by zibo29** [comment] 2020-03-29 18:18
Just done again the playlist trick, changed settings and then respring - I’ll report back if it happens again

**Comment by himynameisubik** [comment] 2020-03-29 18:36
No; like I said, you have to replace it, change a setting (just change appearance) and respring.

**Comment by himynameisubik** [comment] 2020-03-29 22:33
> Here’s mine https://pastebin.com/VST8k3Lz
What I saw now is you didn't update Max. Time Ahead in Up Next. But I can't really find similarities.

**Comment by JJGrootveld** [comment] 2020-03-29 22:35
I’ve been using your plist and haven’t had the bug happen yet. Been using my phone with it for a few hours now..

Want me to test it by going back to my old settings now?

**Comment by zibo29** [comment] 2020-03-29 22:43
I’m also using your plist with some modification to make it similar to my previous setup - didn’t have the bug after 5 hours of usage

**Comment by himynameisubik** [comment] 2020-03-29 22:55
> I’ve been using your plist and haven’t had the bug happen yet. Been using my phone with it for a few hours now..
> 
> Want me to test it by going back to my old settings now? Maybe 1 setting at a time :’)

That would help me out a lot ❤️

**Comment by JJGrootveld** [comment] 2020-03-30 11:00
I have not had it happen ever since moving to your plist file @himynameisubik .

These are the things I changed so far and it feels like im back at my old settings to me. Might be some things enabled that werent before or vice versa. I changed the settings twice:

1. Changed color indicator -  disabled colors - no case conversion - Disable custom scale - changed custom date format
2. Disable time, weather, up next label, up next date in Font weights - set custom scale to 0.86

This is my current plist:
https://pastebin.com/GLmvTSUx

**Comment by himynameisubik** [comment] 2020-03-30 12:34
###I've found the issue, it's caused by the Up Next interval. For whatever reason. I'll look into it. For the meantime, just change Up Next interval to "Always".

**Comment by JJGrootveld** [comment] 2020-03-30 12:36
Damn.. glad you found it! 🎉 makes sense it was something interval based as it happened randomly. Thanks for looking into it with us boss 👊🏻

**Comment by himynameisubik** [comment] 2020-03-30 13:25
Will be fixed in 1.3.4.

**Comment by himynameisubik** [comment] 2020-03-30 13:45
Please let me know if you can confirm @JJGrootveld @zibo29. 
(You can try setting Up Next Interval to something different then always, to see if it happens again)

**Comment by zibo29** [comment] 2020-03-30 14:37
> Please let me know if you can confirm @JJGrootveld @zibo29.
> (You can try setting Up Next Interval to something different then always, to see if it happens again)

Yes I can confirm that, bug came back with that setting turned on. The strange part is that to fix it again I had to put back your plist. Does it makes sense?

**Comment by JJGrootveld** [comment] 2020-03-30 14:55
> Please let me know if you can confirm @JJGrootveld @zibo29.
> (You can try setting Up Next Interval to something different then always, to see if it happens again)

Confirmed just now 👆🏻

**Comment by himynameisubik** [comment] 2020-03-30 14:57
> Yes I can confirm that, bug came back with that setting turned on. The strange part is that to fix it again I had to put back your plist. Does it makes sense?

You can use your plist but change the interval to "Always" and respring, it should work too.

> Confirmed just now 👆🏻

Thanks!

**Comment by zibo29** [comment] 2020-03-30 14:59
Yeah, it’s definitely as you sad - able to reproduce and fix it with the steps above! Thanks a lot!

**Comment by himynameisubik** [comment] 2020-03-30 15:05
> Yeah, it’s definitely as you sad - able to reproduce and fix it with the steps above! Thanks a lot!

Sweet, thanks for the confirmation! Much appreciated @zibo29 @JJGrootveld

**Comment by himynameisubik** [comment] 2020-03-30 15:23
Kalm 1.3.4 was submitted to Packix.

**Closed by himynameisubik** 2020-03-30 15:23 UTC
Labels: bug, next version

**Comment by yonigold1** [comment] 2020-04-10 06:09
hey i’m still having this issue on the latest version of kalm

**Comment by himynameisubik** [comment] 2020-04-10 13:03
> hey i’m still having this issue on the latest version of kalm

Feel free to re-open with all the info.

**Comment by yonigold1** [comment] 2020-04-12 18:09
i’m not sure how to reopen the issue

**Comment by himynameisubik** [comment] 2020-04-12 18:59
Then just create a new ticket with the needed info.
