### ISSUE TITLE
% Charged not showing correctly 

### ISSUE THREAD

**Issue by rkycyku** [himynameisubik/Kalm-support#90] opened 2020-05-25 22:58 UTC
General information:
===

**Kalm version:**
1.3.4

Device information:
===

**iOS version and language:**
12.4.6

**Device:**
iPhone 6

**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**
While charging it doesn’t show the full text it show % Ch...

**How to reproduce:**

1. Put your phone to charge
2. Open Notification Center
3. See error

**Expected behavior:**
It needed to show % Charged 

**Screenshots:**
![AE073BC1-8C39-46C5-967F-70B18BF7226F](https://user-images.githubusercontent.com/48863882/82846900-5d6ab980-9eeb-11ea-9289-36105104c7b5.png)

**Comment by himynameisubik** [comment] 2020-05-26 07:18
Duplicate of #84 . Will be fixed with the next update.

**Closed by himynameisubik** 2020-05-26 07:18 UTC
