### ISSUE TITLE
Not compatible with ProudLock

### ISSUE THREAD

**Issue by crewming22595** [himynameisubik/Kalm-support#19] opened 2020-02-11 12:49 UTC
**Describe the bug**

**How to reproduce**

**Expected behavior**

**Screenshots**

**iOS Version:** 12.1.2

**Device:** iPhone 7

**Device language:** vietnammese

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Additional context**

**Comment by himynameisubik** [comment] 2020-02-11 12:51
Please provide me with a link to ProudLock. I can't get it to work on my iPhone 6 with 12.4.4.

**Comment by himynameisubik** [comment] 2020-02-11 13:01
ProudLock Xr does not work on my phone unfortunately. I can't fix this issue. Maybe try LatchKey, I assume the problem is that ProudLock adds the lock glyph in a different way that I'm checking if there is a lock glyph.

**Comment by himynameisubik** [comment] 2020-02-13 17:11
Closing this issue as no more information was provided.

**Closed by himynameisubik** 2020-02-13 17:11 UTC
Labels: more info, wontfix

**Comment by himynameisubik** [comment] 2020-02-14 12:23
Issue was fixed by downgrading ProudLock Xr to version 1.0. Thanks!
