### ISSUE TITLE
Twitter redirect 

### ISSUE THREAD

**Issue by lucio97** [himynameisubik/Kalm-support#12] opened 2020-02-05 20:32 UTC
**Describe the bug**
Twitter link in the settings is broken.
Is https://mobile.twitter.comhimynameisubik/ instead of https://mobile.twitter.com/himynameisubik/

**How to reproduce**
1. Open settings
2. Click Twitter

**Comment by himynameisubik** [comment] 2020-02-05 21:43
That's really weird, I can't reproduce this, it opens Twitter on my side. Do you have any Browser selector installed?

**Comment by lucio97** [comment] 2020-02-05 22:00
![347E8BE3-D28E-403A-BA34-A803C39E203D](https://user-images.githubusercontent.com/9356159/73887133-3cfaee80-486b-11ea-812c-9a2ca851ee55.jpeg)

**Comment by himynameisubik** [comment] 2020-02-05 22:18
You're right, just deleted Twitter and it doesn't work correctly. Thanks for the report! Will be fixed in the next version.

**Comment by himynameisubik** [comment] 2020-02-06 08:22
Version 1.0.2 was submitted to Packix fixing this issue. Thanks for your report!

**Closed by himynameisubik** 2020-02-06 08:22 UTC
Labels: bug, next version
