### ISSUE TITLE
Springboard crash 

### ISSUE THREAD

**Issue by starraiderx** [himynameisubik/Kalm-support#15] opened 2020-02-08 13:14 UTC
**Describe the bug**
The springboard randomly crashes when waking up the phone 

**Expected behavior**
Springboard crash

**Screenshots**

**iOS Version:**
13.3.1
**Device:**
IPhone X
**Device language:**
English US
**Tweak list:**
Idk how

**Crashlog:**
https://pastebin.com/fxQye6VK
**Additional context**

**Comment by starraiderx** [comment] 2020-02-08 13:15
the reason for the crash is NSConcreteAttributedString initWithString:: nil value

**Comment by himynameisubik** [comment] 2020-02-08 16:59
I can see that yes. Did you disable all other Tweaks besides Kalm in iCleaner and try if this still happens? I can't reproduce this behavior.

**Comment by starraiderx** [comment] 2020-02-08 23:46
It’s very random I don’t know what it causes but mostly when locking my phone before going to sleep so I activate flightmode and sleepcycle

**Comment by starraiderx** [comment] 2020-02-09 06:07
It’s a nul Value from the weather app opening the weather app when it crashes fixes it

**Comment by himynameisubik** [comment] 2020-02-09 09:59
Did you remove the preferences file and disable all other tweaks to test, if this still happens?

**Comment by starraiderx** [comment] 2020-02-09 11:36
Yes

**Comment by himynameisubik** [comment] 2020-02-09 11:53
That's not a problem. Do you have a location manually added to your Weather app?

**Comment by starraiderx** [comment] 2020-02-09 17:22
Yes and would it be possible to change the source from the normal weather app to accuweather?

**Comment by himynameisubik** [comment] 2020-02-09 18:05
I have no idea what this could be. I'll check some more things, that could lead to this, but right now I'm really at a dead end. If you want, you can request a refund, and I'll refund you.

No this isn't a possibility.

**Comment by himynameisubik** [comment] 2020-02-09 18:11
It might be fixed with the next version, but I can't tell since I have no possibility to reproduce this issue. And if you did what I told you, deleting prefs and disabling all other tweaks, I have no idea.

**Comment by starraiderx** [comment] 2020-02-09 20:04
I don’t want a refund I bought the tweak in order to support the development for it. Bc i think the Design is just awesome

**Comment by starraiderx** [comment] 2020-02-09 20:06
BTW it doesn’t happen when I disable the „show weather“ option. Probably this nul value is the temperature nul value I sometimes get in my weather app where it just displays - - instead of a number

**Comment by himynameisubik** [comment] 2020-02-09 22:22
If there is no temperature it also shows -- it just takes the same information from the weather widget. Could you try reinstalling the weather app?

**Comment by starraiderx** [comment] 2020-02-10 14:15
Seems to have fixed the problem thx allot

**Comment by himynameisubik** [comment] 2020-02-10 14:37
Great to hear! Will add this to the general "how to fix" guide. Thanks for bearing with me :)

**Closed by himynameisubik** 2020-02-10 14:37 UTC
Labels: bug, more info
