### ISSUE TITLE
Everything randomly moved up, clips screen border

### ISSUE THREAD

**Issue by sk8erlooser** [himynameisubik/Kalm-support#49] opened 2020-03-18 11:47 UTC
**Packix Username:**
google.110850718543864603685

**Installed version:**
1.3.2

**Describe the bug**
Whole tweak (clock + weather + up next) randomly moves up and clips the phone's screen border.
Doesn't seem to be any gestures that motivates this, as sometimes i just check the time and see everything clipped.

**How to reproduce**
No steps

**Expected behavior**
I expect eveything to stay put

**Screenshots**
![kalm_clip](https://user-images.githubusercontent.com/62335794/76957713-99dfcf00-6916-11ea-93b7-3fc523334c9b.jpg)

**iOS Version:**
13.3.1

**Device:**
Iphone SE

**Device language:**
English

**Tweak list:**
https://pastebin.com/VaP0AWGS

**Crashlog:**
No crashlog

**Additional context:**
Add any other context about the problem

**Comment by himynameisubik** [comment] 2020-03-18 12:05
Thanks for the report, please check existing Reports, this is a duplicate of #45 - Closing.

**Closed by himynameisubik** 2020-03-18 12:05 UTC
