### ISSUE TITLE
Instant safe mode  with “LockWidgets”

### ISSUE THREAD

**Issue by junkFOx-x** [himynameisubik/Kalm-support#46] opened 2020-03-10 20:27 UTC
**Packix Username:**
justinjay

**Installed version:**
Version 1.3.2

**Describe the bug**
The latest version “1.3.2” sends my device to SafeMode while I have the tweak “LockWidgets” installed. 
Downgrading to version “1.3.0” fixes this issue.
Version 1.3.1 also crashes. 

**How to reproduce**
Install LockWidgets from Conor’s repo.

**Expected behavior**
For both tweaks to work together. 🤷🏼‍♂️

**Screenshots**
N/A

**iOS Version:**
iOS 13.3

**Device:**
iPhone XS Max.

**Device language:**
English (Canada)

**Tweak list:**
N/A

**Crashlog:**
https://pastebin.com/xS2JVNBN

**Additional context:**
N/A

**Comment by himynameisubik** [comment] 2020-03-10 21:32
Crashlog clearly indicates the issue is because of LockWidgets. Also a duplicate of #44 please ask the dev of LockWidgets. Strangely enough it works on my devices.

Closing.

**Closed by himynameisubik** 2020-03-10 21:32 UTC

**Comment by junkFOx-x** [comment] 2020-03-11 02:18
But kalm was working fine with LockWidgets before the update. 🤔
Thanks. I’ll report it to the other dev as well. For now I’ll just use an older version of kalm. Cheers 🍻

**Comment by himynameisubik** [comment] 2020-03-11 07:33
Yes, that might be the case but still, it is related to LockWidgets and I can't do anything about that. Sorry!

**Comment by junkFOx-x** [comment] 2020-03-11 16:56
No need to be sorry. :) 
I have sent out an email to Conor. That’s all I can do. 🤷🏼‍♂️ 

Thanks for the replies.
