### ISSUE TITLE
Lock icon half misaligned

### ISSUE THREAD

**Issue by tommoctrl** [himynameisubik/Kalm-support#56] opened 2020-03-28 12:51 UTC
**Packix Username:**
jailbreakitaliadmin
**Installed version:**
1.3.3
**Jailbreak:**
Checkra1n 
**Describe the bug**
After I open the Notification Center half of the lock goes under the battery indicator
**How to reproduce**
Open the Notification Center or turn on the device

**iOS Version:** 
13.3.1

**Device:**
iPhone X (10,6)
**Device language:**
Italian
**Tweak list:**
https://pastebin.com/SStcM9m7

![4C29486B-E22E-4579-92C5-8914635627A1](https://user-images.githubusercontent.com/54364069/77823376-fa32f580-70fa-11ea-84a7-aa08390d8922.jpeg)

**Crashlog:**
None

**Comment by himynameisubik** [comment] 2020-03-28 12:52
Duplicate of #45. Will re-open.

**Closed by himynameisubik** 2020-03-28 12:52 UTC
