### ISSUE TITLE
Kalm and LatchKey Bug:  Lock Icon Position / Color

### ISSUE THREAD

**Issue by paul-michael** [himynameisubik/Kalm-support#111] opened 2020-06-02 03:23 UTC
General information:  
===

**Kalm version:**  v1.4.1

**Kalm preferences file:**
https://pastebin.com/RrMnfTqs

- File location: _/var/mobile/Library/Preferences_ File name: _hi.my.name.is.ubik.kalm.plist_

Device information:
===

**iOS version and language:** 
iOS 13.3

**Device:**
iPhone X

**Jailbreak:**
Checkra1n

Bug description:
===

**Describe the bug:**
The lockscreen lock icon always moves from the default middle position to the custom position (set in latchkey) every unlock. This only happens when both kalm and latchkey is installed. Everything works fine when kalm is disabled via iCleaner. 

Kalm also does not follow the icon color setting set in latchkey.

**How to reproduce:**
1. Set a custom lock icon position in LatchKey.
2. Whenever you unlock device, the lock icon would slide to the middle default position then slide back into the custom set position.
3. Disabled all tweaks in iCleaner (except for latchkey) and enable again 1 by 1. Problem only happens when Kalm is enabled back on. 

**Expected behavior:**
The lock icon should stay in place and not move around.

**Screenshots:**
https://www.dropbox.com/s/mr95zmqj31bzecr/IMG_0408.MOV?dl=0

Additional information:
===

**Tweak list:**
Put it on www.pastebin.com

**Crashlog:**
Put it on www.pastebin.com

**Comment by himynameisubik** [comment] 2020-06-02 08:12
Duplicate of #110

**Closed by himynameisubik** 2020-06-02 08:12 UTC
