### ISSUE TITLE
Sometimes Kalm moves upwards

### ISSUE THREAD

**Issue by Evertt** [himynameisubik/Kalm-support#62] opened 2020-04-02 09:16 UTC
Device: iPhone X
iOS version: 13.4
Jailbroken with checkra1n 0.9.9
Kalm version: 1.3.3

**Description**
Once in a while, when I wake my phone, the Kalm widget is moved upwards. Like so:

![IMG_5816](https://user-images.githubusercontent.com/1267282/78231262-d264d880-74d2-11ea-9671-8007e8139880.PNG)

Even though this is its normal position:

![IMG_B388ADA96DCA-1](https://user-images.githubusercontent.com/1267282/78231321-ead4f300-74d2-11ea-8844-b1567825a918.jpeg)

After I slide up to go to the home screen and then slide notification center back down then Kalm is back in its normal place.

There is no crash report for this obviously. Also I'm guessing this has nothing to do with my preferences. And it doesn't happen every time I unlock my phone, just sometimes. I haven't really found a pattern in it yet.

**Comment by himynameisubik** [comment] 2020-04-02 13:30
Duplicate of #45 and was fixed in 1.3.4.

**Closed by himynameisubik** 2020-04-02 13:30 UTC
