### ISSUE TITLE
SB Crash on first boot with checkra1n

### ISSUE THREAD

**Issue by nicobargit** [himynameisubik/Kalm-support#28] opened 2020-02-14 10:41 UTC
**Descrive the bug**
SpringBoard crashes on checkra1n jailbreak boot

**How to reproduce**
1. Only enable Kalm in iCleaner
2. Put in DFU
3. Run checkra1n
4. SpringBoard is in safe mode now = crash

**iOS Version:**
13.3
**Device:**
iPhone X
**Device language:**
English
**Tweak list:**
Only Kalm is enabled

**Comment by himynameisubik** [comment] 2020-02-14 10:48
Please provide a crashlog

**Comment by himynameisubik** [comment] 2020-02-14 10:55
Also, did you follow these steps already:

1. Try reinstalling the stock Weather app from Apple.
2. Try disabling all Tweaks except Kalm in iCleaner to check if there is a conflicting tweak.
3. Try removing the Kalm preferences file hi.my.name.is.ubik.kalm.plist in /var/mobile/Library/Preferences and respring.

**Comment by nicobargit** [comment] 2020-02-14 11:03
> Please provide a crashlog

Crashed doesn’t provide the crash log for this bug

**Comment by himynameisubik** [comment] 2020-02-14 11:05
That's really weird. Did you try the steps above?

**Comment by nicobargit** [comment] 2020-02-14 11:10
> That's really weird. Did you try the steps above?
n.2 seems to fixed the issue, thank you

**Comment by himynameisubik** [comment] 2020-02-14 11:13
Sweet, thanks for the update and glad it worked out :)

**Comment by nicobargit** [comment] 2020-02-14 11:14
> Sweet, thanks for the update and glad it worked out :)

Jees wait, if you boot without preferences it works. If you boot with preferences it crashes

**Comment by himynameisubik** [comment] 2020-02-14 11:15
Hmm, can you attach your preferences file please?

**Comment by nicobargit** [comment] 2020-02-14 11:19
I'm currently trying to reboot with the .plist generated by adjusting alignment to center. I'll send you the preferences files if it doesn't work

**Comment by nicobargit** [comment] 2020-02-14 11:21
Now it's working, i think its 100% related with a configuration.

**Comment by himynameisubik** [comment] 2020-02-14 11:23
Weird, can you please update this issue as soon as you run into this again?

**Comment by nicobargit** [comment] 2020-02-14 11:24
Ok, if i enable show position and show location in weather settings the sb crash on boot

**Comment by nicobargit** [comment] 2020-02-14 11:25
Of course if i respring after boot everything works fine

**Comment by himynameisubik** [comment] 2020-02-14 11:26
"Show position"? Do you mean "Show condition"? Could you please check if it is both combined, or only one of them causing your issue? 
Because I'm also using this setting and I couldn't recreate the issue.

**Comment by himynameisubik** [comment] 2020-02-14 11:26
And you said no crashlogs right?

**Comment by nicobargit** [comment] 2020-02-14 11:26
> And you said no crashlogs right?

Right

**Comment by nicobargit** [comment] 2020-02-14 11:28
> "Show position"? Do you mean "Show condition"? Could you please check if it is both combined, or only one of them causing your issue?
> Because I'm also using this setting and I couldn't recreate the issue.

Yes sorry it was condition, i'm trying to isolate the bug. If i don't delete the preference file and i disable show location and show condition it boots fine. I'll try with one on and the other off

**Comment by nicobargit** [comment] 2020-02-14 11:33
Show Location on and Show Condition off don't crash the sb on boot.
Show Location off and Show Condition on do.
Both on do.
Both off don't.
It's related to Show condition option.

**Comment by nicobargit** [comment] 2020-02-14 11:36
If you need I can send you some files or configurations

**Comment by himynameisubik** [comment] 2020-02-14 11:44
All right, thank you very much for that! I'll checkout what it could be with the condition. Really stupid question, what is the condition at the moment? :)

**Comment by nicobargit** [comment] 2020-02-14 11:47
> All right, thank you very much for that! I'll checkout what it could be with the condition. Really stupid question, what is the condition at the moment? :)

I don't think its related to the condition rn becuse i'm experiencing this issue since the first releases. Btw it's "Mostly Sunny" right now. Maybe, can you try loading conditions after sb is loaded?

**Comment by himynameisubik** [comment] 2020-02-14 11:50
Sure no worries, thanks for the info. Will try to reproduce and look into it.

**Comment by himynameisubik** [comment] 2020-02-14 11:53
Sorry for asking again, but did you try to reinstall the weather app?

**Comment by nicobargit** [comment] 2020-02-14 11:56
> Sorry for asking again, but did you try to reinstall the weather app?

Yes, I can try one more time if needed

**Comment by nicobargit** [comment] 2020-02-14 11:57
What if I boot without the weather app?

**Comment by himynameisubik** [comment] 2020-02-14 11:58
Hmm, it doesn't crash on my two devices with that setting enabled. That's really strange. Do you have a location set manually in the weather app or are you only using Location Services?

**Comment by nicobargit** [comment] 2020-02-14 11:58
i'm only using location services

**Comment by himynameisubik** [comment] 2020-02-14 11:59
Please manually add a location and try again. (You can add whatever random location)

**Comment by himynameisubik** [comment] 2020-02-14 11:59
It should update to the location services location after showing the screen again.

**Comment by nicobargit** [comment] 2020-02-14 12:06
I did these steps:
1) reinstalled weather
2) after reinstall no location based on gps are shown but after opening the locations menu the gps based location come out. 
3) I added London location but Kalm still show me the gps one based on the lockscreen.
4) Rebooted with checkra1n but the problem still

**Comment by nicobargit** [comment] 2020-02-14 12:07
For me this bug isn't a big deal as you can fix with a simple respring, i only wanted to report this to you

**Comment by himynameisubik** [comment] 2020-02-14 12:11
All right, thanks for the report. I'll check it out deeper if I can somehow reproduce it and find out how to fix this issue.

**Comment by nicobargit** [comment] 2020-02-14 12:17
On my iPad6,4 iOS 13.2 I don't have this problem. Maybe I can fix this by restoring my iPhone X.
Btw Thank you for your support and keep up your great work

**Comment by himynameisubik** [comment] 2020-02-14 12:19
If you can try, sure go for it. Else maybe I can hack something around that might fix it – if you can wait a little :-)

Thanks for your great help in trying to debug the issue!

**Comment by nicobargit** [comment] 2020-02-14 12:21
Yes I'll wait, I really want to avoid data lost.
If no fix came out I will survive by doing a simple and quick respring after boot. Thank you again!

**Comment by himynameisubik** [comment] 2020-02-14 13:29
All right, and without the condition enabled it works fine, right?

**Comment by nicobargit** [comment] 2020-02-14 14:06
> All right, and without the condition enabled it works fine, right?

Yes, with condition off I’m not facing this issue at all

**Comment by nicobargit** [comment] 2020-02-14 17:17
I've installed crash reporter and it does log the crash! 
Here it is: 
[https://pastebin.com/BmundRhw](https://pastebin.com/BmundRhw)

**Comment by himynameisubik** [comment] 2020-02-14 19:41
Thanks! Seems like I can actually recreate it. Seems the problem is the data is not available after the checkra1n restart, so I won't load it on the first instance but after you unlocked your device and lock it again/drag down the coversheet. That fixes that problem :)

**Comment by nicobargit** [comment] 2020-02-14 20:29
> > All right, thank you very much for that! I'll checkout what it could be with the condition. Really stupid question, what is the condition at the moment? :)
> 
> I don't think its related to the condition rn becuse i'm experiencing this issue since the first releases.
> Btw it's "Mostly Sunny" right now.
> Maybe, can you try loading conditions after sb is loaded?
> (Could be a stupid suggestion because I don't know anything in the code)
> And sorry for my english, it's not my main



> Thanks! Seems like I can actually recreate it. Seems the problem is the data is not available after the checkra1n restart, so I won't load it on the first instance but after you unlocked your device and lock it again/drag down the coversheet. That fixes that problem :)

After all my suggestion wasn’t that stupid 😆. I think we can close the issue! Thank you keep Kalm up!

**Comment by himynameisubik** [comment] 2020-02-14 21:00
Haha yeah! :) Well I hope so, I'll close it once the update is live and submitted. :)

**Comment by catalyst7even** [comment] 2020-02-15 19:28
What version is this fixed in or has it not been submitted yet?

**Comment by himynameisubik** [comment] 2020-02-15 21:35
Oh I didn't see it was closed by the issue creator. It is in testing at the moment and should be released soon. Reopening it until it will actually be fixed.

**Comment by catalyst7even** [comment] 2020-02-15 22:09
Thanks!

**Comment by himynameisubik** [comment] 2020-02-17 08:35
1.2.2 was submitted to Packix. Hopefully that will fix this issue.

**Comment by himynameisubik** [comment] 2020-02-17 17:36
1.2.2 is out. Let me know if that fixes the issue for you :)
https://repo.packix.com/package/hi.my.name.is.ubik.kalm/

**Comment by Cinyk** [comment] 2020-02-17 19:43
I am still having those issues on X 13.3.1 even with the latest version unfortunately.
Reinstalling weather.app and deleting the config file doesn't help. 
Respringing doesn't help I get sent in a bootloop and have to re-checkra1n to safe mode
Also with the tweak being the only one enabled in iCleaner

**Comment by himynameisubik** [comment] 2020-02-17 19:48
Could you please attach a crashlog?

**Comment by nicobargit** [comment] 2020-02-17 19:53
> 1.2.2 is out. Let me know if that fixes the issue for you :)
> https://repo.packix.com/package/hi.my.name.is.ubik.kalm/

The issue is gone for me, thank you

**Comment by himynameisubik** [comment] 2020-02-17 19:53
> The issue is gone for me, thank you
Thanks for the reply! Glad it works for you!

**Comment by Cinyk** [comment] 2020-02-17 19:54
Not sure how to generate one as I straight bootloop if I try getting out of same mode after booting with checkra1n. If I boot with the Safe mode option toggled in checkra1n, nothing in cr4shed and reinstalling substrate also bootloops =.="

**Comment by himynameisubik** [comment] 2020-02-17 19:58
> Not sure how to generate one as I straight bootloop if I try getting out of same mode after booting with checkra1n. If I boot with the Safe mode option toggled in checkra1n, nothing in cr4shed and reinstalling substrate also bootloops =.="

Reinstalling substrate bootloops? This sounds like a different issue tho.

**Comment by Cinyk** [comment] 2020-02-17 19:59
I meant reinstalling substrate to be in normal jailbreak mode after using checkra1n's safe mode toggle. Was just saying whatever I do with kalm installed it bootloops and I can't seem to get a crash log

**Comment by himynameisubik** [comment] 2020-02-17 20:00
Can you provide a tweaklist?

**Comment by himynameisubik** [comment] 2020-02-18 10:16
Closing this issue as it was fixed.

If anyone else runs into the problem, feel free to comment.

**Closed by himynameisubik** 2020-02-18 10:16 UTC
Labels: bug, noETA

**Comment by catalyst7even** [comment] 2020-02-18 16:40
Fixed it for me. Thanks!
