### ISSUE TITLE
Cannot disable color of Day/Time in Up Next

### ISSUE THREAD

**Issue by paul-michael** [himynameisubik/Kalm-support#14] opened 2020-02-07 19:35 UTC
**Describe the bug**
Day & Time portion in Up Next is still colored (light pink in screenshot) even if it’s disabled in settings. 

**How to reproduce**
1. Disable color option in settings. 

**Expected behavior**
Color of all labels should be white.

**Screenshots**
https://imgur.com/a/WwDdSbz

**iOS Version:**
iOS 13.3

**Device:**
This happens on both my iPhone X and iPhone 6s Plus both on the same iOS version. 

**Device language:**
English

**Tweak list:**
Either attach it as a text file or put it on pastebin.com

**Crashlog:**
Either attach it as a text file or put it on pastebin.com

**Additional context**

**Comment by himynameisubik** [comment] 2020-02-07 20:08
Did you respring after the change?

**Comment by catalyst7even** [comment] 2020-02-09 14:55
I have the same issue which I described on r/jailbreak. I did respring, rebooted etc. I checked the preference file in Filza and the color option was off. Obviously my wallpaper background is different than the other user but the color of the label is the same shown in his screenshot

**Comment by himynameisubik** [comment] 2020-02-09 15:16
Can you delete the prefs file? It's a really weird issue on my end since I can't reproduce it. Sorry for the inconvenience.

**Comment by paul-michael** [comment] 2020-02-09 21:13
I already tried uninstalling, then deleting the preference file using icleaner, then re-installing again. Still the same light pink-ish color just on the day/time portion even after disabling the option in settings. 

I understand that you may not be able to re-produce the problem as it only happens on my iPhone X. My iPhone 6s Plus and iPad Air 2 does not show this bug and my iPhone 6s has almost the same tweaks as my iPhone X as the 6s is my test device before installing installing tweaks on my X.

Not a big issue for me personally as it is a very light-ish color, very close to white. Hopefully the bug goes away if ever you add the option for us to change the various elements with specific colors of our choosing :)

**Comment by catalyst7even** [comment] 2020-02-09 21:16
Yes, same thing. Your prefs file defaults to color on after respring. After adjusting settings, apply & respring, the upNext date label is still Pinkish colored.

**Comment by himynameisubik** [comment] 2020-02-09 22:30
My problem is, I can't reproduce it on my iPhone 6 on 12.4, my SE, 8 and X on 13.3 :'D
However, I changed something in the next version 1.1.0 and hopefully that will also work on your X device. Sorry for that.

I assume you both tried changing the wallpaper already?

**Comment by catalyst7even** [comment] 2020-02-09 22:53
Yes, it’s still a pink looking label with other wallpaper. It would be nice for it to be white, but it’s not a deal breaker. I’m enjoying it as is

**Comment by himynameisubik** [comment] 2020-02-10 07:57
Wait what? Even if you have a totally different wallpaper it's pink?

**Comment by catalyst7even** [comment] 2020-02-10 15:06
Yes, it is. I tried two that were blackish, one all black, the other grayish black and both had the pink label.

**Comment by himynameisubik** [comment] 2020-02-10 15:07
Okay that's like really weird :D That makes no sense at all. But I really hope it will be fixed in the 1.1.0 update.

**Comment by catalyst7even** [comment] 2020-02-13 14:47
Haven’t fiddled with any settings yet but the latest update appears to have fixed it

**Comment by himynameisubik** [comment] 2020-02-13 14:51
Sweet, great to hear. Closing this as it was fixed in 1.2.0. Thanks for the update!

**Closed by himynameisubik** 2020-02-13 14:51 UTC
Labels: bug
